/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wry;

public class App {
    public static void main(String[] args) {
        new Thread(() -> {
            try {
                SyncNonblockingServer.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
}
